export async function readSyncSources(config,googleGet,now=new Date()){
 const sourceError=(message,code)=>{throw Object.assign(new Error(message),{status:503,code});};
 const timeMin=new Date(now.getTime()-7*86400000).toISOString(),timeMax=new Date(now.getTime()+56*86400000).toISOString();
 const rows=(data,required,limit)=>{const values=data.values;if(!Array.isArray(values)||!values.length)sourceError('Tracker tab is empty or unreadable.','tracker_unreadable');const headers=values[0].map(v=>String(v).trim());if(required.some(h=>!headers.includes(h))||new Set(headers.filter(Boolean)).size!==headers.filter(Boolean).length)sourceError('Tracker columns changed; review the mapping.','tracker_columns_changed');if(values.length>=limit)sourceError('Tracker range limit reached; extend the verified read bounds.','tracker_range_limit');return values.slice(1).map((r,index)=>({r,index})).filter(({r})=>r.some(v=>String(v).trim())).map(({r,index})=>({...Object.fromEntries(headers.map((h,i)=>[h,r[i]??'']).filter(([h])=>h)),_row:index+2}));};
 const base='https://sheets.googleapis.com/v4/spreadsheets/'+encodeURIComponent(config.spreadsheetId)+'/values/';
 const students=rows(await googleGet(base+encodeURIComponent('Students!A1:AD1000')),['Student','Rate','Currency'],1000);
 const lessons=rows(await googleGet(base+encodeURIComponent('Lessons!A1:Y1001')),['Student','Lesson Date','Status','Lesson Focus','Homework / Next Step'],1001);
 const billing=rows(await googleGet(base+encodeURIComponent('Billing!A1:AF998')),['Student','Invoice Date','Status'],998);
 let pageToken='',events=[];const seen=new Set();do{const q=new URLSearchParams({singleEvents:'true',showDeleted:'true',timeMin,timeMax,timeZone:'America/Toronto',maxResults:'2500'});if(pageToken)q.set('pageToken',pageToken);const page=await googleGet('https://www.googleapis.com/calendar/v3/calendars/'+encodeURIComponent(config.calendarId)+'/events?'+q);if(!Array.isArray(page.items))sourceError('Calendar response is incomplete.','calendar_incomplete');events.push(...page.items);pageToken=page.nextPageToken||'';if(pageToken&&(seen.has(pageToken)||seen.size>=20))sourceError('Calendar pagination could not finish.','calendar_pagination_incomplete');seen.add(pageToken);}while(pageToken);
 return {complete:true,calendarId:config.calendarId,spreadsheetId:config.spreadsheetId,students,lessons,billing,events,timeMin,timeMax};
}
