"""JSON is valid YAML; generated config has no package dependency."""
def field(name,label,widget='string',**kwargs): return dict(name=name,label=label,widget=widget,**kwargs)
def blocks():
    return field('blocks','Page content','list',allow_add=False,allow_delete=False,allow_reorder=False,summary='{{fields.label}}',fields=[field('key','Key','hidden'),field('label','Section','hidden'),field('text','Text','text')])
def make_config(settings,routes):
    files=[dict(name='page-'+r['name'],label='Home' if r['name']=='home' else r['name'].replace('-',' ').title(),file='content/pages/'+r['name']+'.json',fields=[field('title','Browser title'),field('description','Search description','text'),blocks()]) for r in routes if r['name']!='404']
    shared=[dict(name=n,label={'header':'Menu labels','footer':'Footer','cta':'Shared enquiry section'}[n],file='content/'+n+'.json',fields=[blocks()]) for n in ['header','footer','cta']]
    shared.append(dict(name='settings',label='Contact details and images',file='content/settings.json',fields=[field('site_url','Website address','hidden'),field('github_repository','Repository','hidden'),field('github_branch','Branch','hidden'),field('production','Launch mode','hidden'),field('turnstile_site_key','Spam protection','hidden',required=False),field('public_email','Public email',required=False),field('portrait','Amanda photograph','image',required=False),field('portrait_alt','Photo description'),field('logo','Logo','image')]))
    rec=dict(name='recommendations',label='Recommendations',file='content/recommendations.json',fields=[field('source_document','Source document','hidden'),field('verification_url','LinkedIn verification link'),field('recommendations','Recommendations','list',summary='{{fields.name}}',fields=[field('id','Unique ID',hint='Keep existing IDs unchanged. Use a short unique word for new recommendations.'),field('name','Name'),field('relationship','Relationship'),field('date','Date','datetime',date_format='YYYY-MM-DD',time_format=False,format='YYYY-MM-DD'),field('display_date','Date as displayed'),field('topic','Card heading'),field('group','Section','select',options=['parents','students','colleagues']),field('screenshot_page','Source page','number',required=False,value_type='int'),field('quote','Recommendation text','text'),field('short_quote','Homepage excerpt','text',required=False)])])
    repo=settings.get('github_repository') or 'CONFIGURE/REPOSITORY'
    config={'backend':{'name':'github','repo':repo,'branch':settings.get('github_branch','main'),'base_url':settings.get('site_url') or 'https://configure.example','auth_endpoint':'api/auth'},'media_folder':'public/assets/uploads','public_folder':'/assets/uploads','publish_mode':'editorial_workflow','collections':[{'name':'pages','label':'Website pages','files':files},{'name':'shared','label':'Shared content','files':shared},{'name':'recommendation-content','label':'Recommendations','files':[rec]}]}
    if settings.get('site_url'): config.update(site_url=settings['site_url'],display_url=settings['site_url'])
    return config
