// Authorized Cloudflare-native cutover. No business/source/financial writes.
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {createHash,randomBytes,createCipheriv} from 'node:crypto';
import {open} from '../cloudflare/crypto.js';
function sealBackup(secret,text){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',createHash('sha256').update(secret).digest(),iv),encrypted=Buffer.concat([cipher.update(text,'utf8'),cipher.final(),cipher.getAuthTag()]);return iv.toString('base64url')+'.'+encrypted.toString('base64url');}
const account='2ac862d7c1f865935d185df59e7bd719',stageDb='4f12fc1d-3e0d-4a11-bd65-e577ce906114',project='auxesis-education',origin='https://auxesis-education.pages.dev';
const dir='work/production-cutover',stageDir='work/staging-deployment';
const require=(ok,s)=>{if(!ok)throw Error(s);};
const canonical=v=>v===undefined?'null':JSON.stringify(v&&typeof v==='object'?Array.isArray(v)?v.map(x=>JSON.parse(canonical(x))):Object.fromEntries(Object.keys(v).sort().map(k=>[k,JSON.parse(canonical(v[k]))])):v);
let target,phase='initial';
async function cf(path,method='GET',body){
 const allowed=method==='GET'||method==='POST'&&path==='/d1/database'&&body?.name==='auxesis-live-portal'||method==='POST'&&[stageDb,target].includes(path.split('/')[3])&&path.endsWith('/query')||method==='PATCH'&&path==='/pages/projects/'+project||method==='POST'&&path.startsWith('/pages/projects/'+project+'/deployments/')&&path.endsWith('/rollback');
 require(allowed,'Cutover write target rejected.');
 const r=await fetch('https://api.cloudflare.com/client/v4/accounts/'+account+path,{method,redirect:'error',headers:{Authorization:'Bearer '+process.env.CLOUDFLARE_API_TOKEN,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});require(r.ok,'Cutover provider HTTP '+r.status+' during '+phase);const j=await r.json();require(j.success,'Cutover provider rejected request.');return j.result;
}
const query=async(db,sql,params)=>(await cf('/d1/database/'+db+'/query','POST',{sql,...(params?{params}:{})})).flatMap(x=>x.results||[]);
async function drive(){const grant=(await query(stageDb,"SELECT email,client_id,refresh_token_ciphertext FROM migration_google_authorization WHERE id='owner'"))[0],key=(await query(stageDb,"SELECT secret FROM portal_release_keys WHERE id='migration-transport'"))[0]?.secret;require(grant&&key,'Private recovery authorization absent.');const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',redirect:'error',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',client_id:grant.client_id,client_secret:process.env.GOOGLE_CLIENT_SECRET,refresh_token:await open(key,grant.refresh_token_ciphertext)})});require(r.ok,'Private recovery authorization failed.');return {key,access:(await r.json()).access_token};}
async function savePrivate(name,bytes,access){const boundary='auxesis-'+randomBytes(12).toString('hex');const body=Buffer.concat([Buffer.from('--'+boundary+'\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n'+JSON.stringify({name,mimeType:'application/json',appProperties:{auxesisPurpose:'production-cutover-recovery'}})+'\r\n--'+boundary+'\r\nContent-Type: application/json\r\n\r\n'),bytes,Buffer.from('\r\n--'+boundary+'--\r\n')]);const headers={Authorization:'Bearer '+access};const r=await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id',{method:'POST',redirect:'error',headers:{...headers,'Content-Type':'multipart/related; boundary='+boundary},body});require(r.ok,'Private cutover recovery save failed.');const id=(await r.json()).id,url='https://www.googleapis.com/drive/v3/files/'+encodeURIComponent(id);const meta=await fetch(url+'?fields=ownedByMe,shared,permissions,size',{headers,redirect:'error'});require(meta.ok,'Private recovery metadata unreadable.');const m=await meta.json();require(m.ownedByMe&&!m.shared&&(m.permissions||[]).every(p=>p.type==='user'&&p.role==='owner')&&Number(m.size)===bytes.length,'Private recovery privacy/size failed.');const back=await fetch(url+'?alt=media',{headers,redirect:'error'});require(back.ok,'Private recovery readback failed.');require(createHash('sha256').update(Buffer.from(await back.arrayBuffer())).digest('hex')===createHash('sha256').update(bytes).digest('hex'),'Private recovery checksum mismatch.');return id;}
async function prepare(){
 require(process.env.GITHUB_REPOSITORY==='Amandadsouza77/auxesis-education'&&process.env.GITHUB_REF==='refs/heads/codex/cloudflare-backend-migration','Unexpected authorized cutover branch.');
 const before=JSON.parse(readFileSync(stageDir+'/before.json')),live=await cf('/pages/projects/'+project),stage=await cf('/pages/projects/auxesis-production-staging');
 require(canonical({configs:live.deployment_configs,deployment:live.canonical_deployment?.id})===canonical(before.production)&&live.production_branch==='main','Production changed after private package preparation.');
 require(['GOOGLE_CLIENT_ID','GOOGLE_CLIENT_SECRET','PORTAL_TOKEN_KEY'].every(k=>live.deployment_configs.production.env_vars?.[k]),'Production credential bindings absent.');
 const client=stage.deployment_configs.preview.env_vars.GOOGLE_CLIENT_ID.value;
 const auth=new URL('https://accounts.google.com/o/oauth2/v2/auth');auth.search=new URLSearchParams({client_id:client,redirect_uri:origin+'/api/portal/auth/callback',response_type:'code',scope:'openid email profile',state:'cutover-preflight',code_challenge:'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',code_challenge_method:'S256'});const check=await fetch(auth,{redirect:'follow'}),text=await check.text();const callbackAccepted=check.ok&&!/redirect_uri_mismatch|invalid_client/.test(text+decodeURIComponent(check.url))&&!new URL(check.url).pathname.includes('/error');
 phase='isolated-database';const databases=await cf('/d1/database');const found=databases.find(d=>d.name==='auxesis-live-portal');const database=found||await cf('/d1/database','POST',{name:'auxesis-live-portal'});target=database.uuid;require(target&&target!==stageDb&&!Object.values(live.deployment_configs).some(c=>Object.values(c.d1_databases||{}).some(v=>v.id===target))&&!Object.values(stage.deployment_configs).some(c=>Object.values(c.d1_databases||{}).some(v=>v.id===target)),'Clone target must not be bound to live or staging.');
 phase='clone-schema';const sourceRecords=structuredClone(before.records);const settingsRow=before.records.find(r=>r.id==='settings'),settingsData=JSON.parse(settingsRow.data);settingsData.productionRelease.databaseId=target;settingsRow.data=JSON.stringify(settingsData);settingsRow.revision++;
 for(const file of ['cloudflare/migrations/0001_portal.sql','cloudflare/migrations/0002_portal_runtime.sql','cloudflare/migrations/0003_pilot_runtime.sql','scripts/production-sync-schema.sql']){
  for(const statement of readFileSync(file,'utf8').split(/;(?=\s*(?:CREATE|ALTER|$))/).filter(s=>s.trim())){if(statement.trim().startsWith('ALTER TABLE portal_auth_flows')&&(await query(target,'PRAGMA table_info(portal_auth_flows)')).some(c=>c.name==='payload'))continue;await query(target,statement);}
 }
 const columns=await query(target,'PRAGMA table_info(portal_accounts)');for(const c of ['provider_id','created_at'])if(!columns.some(x=>x.name===c))await query(target,'ALTER TABLE portal_accounts ADD COLUMN '+c+' TEXT');
 // Inserts only; a resumed target must match before any new inserts.
 const existing=await query(target,'SELECT * FROM portal_records ORDER BY id');for(const r of existing)require(before.records.some(x=>canonical(x)===canonical(r))||(r.id==='settings'&&sourceRecords.some(x=>canonical(x)===canonical(r))),'Existing clone differs; no overwrite permitted.');
 const insert=async(table,rows)=>{if(!rows.length)return;const cols=Object.keys(rows[0]);require(cols.every(c=>/^[a-z_]+$/.test(c)),'Invalid source columns.');for(let i=0;i<rows.length;i+=8){const chunk=rows.slice(i,i+8),params=chunk.flatMap(r=>cols.map(c=>r[c]));await query(target,'INSERT INTO '+table+'('+cols.join(',')+') VALUES '+chunk.map((r,j)=>'('+cols.map((c,k)=>'?'+(j*cols.length+k+1)).join(',')+')').join(',')+' ON CONFLICT(id) DO NOTHING',params);}};
 phase='clone-records';await insert('portal_records',before.records);phase='clone-accounts';await insert('portal_accounts',before.accounts);phase='clone-audits';await insert('portal_audit',before.audits);
 const originalSettings=sourceRecords.find(r=>r.id==='settings');await query(target,"UPDATE portal_records SET data=?1,revision=?2 WHERE id='settings' AND data=?3 AND revision=?4",[settingsRow.data,settingsRow.revision,originalSettings.data,originalSettings.revision]);
 for(const [table,expected] of [['portal_records',before.records],['portal_accounts',before.accounts],['portal_audit',before.audits]])require(canonical(await query(target,'SELECT * FROM '+table+' ORDER BY id'))===canonical(expected),'Live clone integrity differs.');
 phase='clone-integrity';const integrity=await query(target,'PRAGMA quick_check');require(integrity.length===1&&Object.values(integrity[0])[0]==='ok','Live database integrity failed.');
 phase='private-recovery';const authorization=await drive(),savedAt=new Date().toISOString(),snapshot={live,stage,records:before.records,sourceRecords,accounts:before.accounts,audits:before.audits,targetDatabase:target};
 const retained=(await query(stageDb,"SELECT * FROM migration_cutover_recovery WHERE id='production'"))[0];let fileId,recoverySha,reusedRecovery=false;
 if(retained&&retained.target_database===target){
  const url='https://www.googleapis.com/drive/v3/files/'+encodeURIComponent(retained.file_id),headers={Authorization:'Bearer '+authorization.access};const meta=await fetch(url+'?fields=ownedByMe,shared,permissions,size',{headers,redirect:'error'});require(meta.ok,'Existing recovery metadata unavailable.');const m=await meta.json();require(m.ownedByMe&&!m.shared&&(m.permissions||[]).every(p=>p.type==='user'&&p.role==='owner')&&Number(m.size)<8*1024*1024,'Existing recovery privacy failed.');const raw=await fetch(url+'?alt=media',{headers,redirect:'error'});require(raw.ok,'Existing recovery readback unavailable.');const bytes=Buffer.from(await raw.arrayBuffer());require(createHash('sha256').update(bytes).digest('hex')===retained.sha256,'Existing recovery checksum differs; cutover stopped.');const envelope=JSON.parse(bytes.toString()),prior=JSON.parse(await open(authorization.key,envelope.ciphertext));
  const fingerprint=x=>({records:x.records,sourceRecords:x.sourceRecords,accounts:x.accounts,audits:x.audits,targetDatabase:x.targetDatabase,live:{configs:x.live.deployment_configs,source:x.live.source,branch:x.live.production_branch,deployment:x.live.canonical_deployment?.id},stage:{configs:x.stage.deployment_configs,deployment:x.stage.canonical_deployment?.id}});
  require(canonical(fingerprint(prior))===canonical(fingerprint(snapshot)),'Prepared recovery differs from current data/configuration; no silent overwrite.');fileId=retained.file_id;recoverySha=retained.sha256;reusedRecovery=true;
 }else{const bytes=Buffer.from(JSON.stringify({format:'auxesis-cutover-encrypted-v1',createdAt:savedAt,ciphertext:sealBackup(authorization.key,JSON.stringify(snapshot))}));fileId=await savePrivate('Auxesis encrypted production cutover recovery '+savedAt+'.json',bytes,authorization.access);recoverySha=createHash('sha256').update(bytes).digest('hex');}
 await query(stageDb,'CREATE TABLE IF NOT EXISTS migration_cutover_recovery(id TEXT PRIMARY KEY,file_id TEXT NOT NULL,sha256 TEXT NOT NULL,target_database TEXT NOT NULL,created_at TEXT NOT NULL)');if(!reusedRecovery)await query(stageDb,"INSERT INTO migration_cutover_recovery(id,file_id,sha256,target_database,created_at) VALUES('production',?1,?2,?3,?4) ON CONFLICT(id) DO UPDATE SET file_id=excluded.file_id,sha256=excluded.sha256,target_database=excluded.target_database,created_at=excluded.created_at",[fileId,recoverySha,target,savedAt]);
 mkdirSync(dir,{recursive:true});writeFileSync(dir+'/before.json',JSON.stringify({live,stage,target,records:before.records,accounts:before.accounts,audits:before.audits}),{mode:0o600});
 const entry=`import {handlePortalRequest} from './cloudflare/runtime.js';\nconst ORIGIN='${origin}';\nexport default {async fetch(request,env){const u=new URL(request.url);if(env.PORTAL_RUNTIME_MODE!=='production'||env.PORTAL_STAGING_ONLY==='true'||env.PRODUCTION_ORIGIN!==ORIGIN||env.PRODUCTION_SYNC_ENABLED!=='false'||env.PRODUCTION_AUTOMATION_ENABLED!=='false'||u.origin!==ORIGIN)return new Response('Portal unavailable',{status:503,headers:{'Cache-Control':'no-store'}});if(u.pathname.startsWith('/api/portal/'))return handlePortalRequest({request,env,params:{path:u.pathname.slice('/api/portal/'.length).split('/')}});return env.ASSETS.fetch(request);}};\n`;
 writeFileSync(stageDir+'/runtime/production-entry.js',entry,{mode:0o600});
 console.log('::notice title=Production cutover prepared::'+JSON.stringify({productionCallbackAccepted:callbackAccepted,separateLiveDatabase:true,preservedRecords:371,preservedStudents:15,preservedLessons:200,preservedInvoices:16,preservedPayments:9,integrityCheck:'ok',encryptedPrivateRecoveryReadbackVerified:true,existingRecoveryReused:reusedRecovery,productionDeploymentUnchanged:true,applyEnabled:false,automationEnabled:false}));
 require(callbackAccepted,'Production OAuth callback is still rejected; encrypted recovery and live clone are prepared, original deployment retained.');
}
const touched=['PORTAL_RUNTIME_MODE','PORTAL_STAGING_ONLY','PRODUCTION_ORIGIN','PORTAL_DB_ID','ADMIN_EMAIL','GOOGLE_SPREADSHEET_ID','GOOGLE_CALENDAR_ID','PRODUCTION_SYNC_ENABLED','PRODUCTION_AUTOMATION_ENABLED'];
async function activate(){const before=JSON.parse(readFileSync(dir+'/before.json'));target=before.target;const live=await cf('/pages/projects/'+project);require(canonical(live.deployment_configs)===canonical(before.live.deployment_configs)&&live.canonical_deployment?.id===before.live.canonical_deployment?.id,'Production changed before binding.');const stageVars=before.stage.deployment_configs.preview.env_vars,values={PORTAL_RUNTIME_MODE:'production',PORTAL_STAGING_ONLY:'false',PRODUCTION_ORIGIN:origin,PORTAL_DB_ID:target,ADMIN_EMAIL:stageVars.ADMIN_EMAIL.value,GOOGLE_SPREADSHEET_ID:stageVars.GOOGLE_SPREADSHEET_ID.value,GOOGLE_CALENDAR_ID:stageVars.GOOGLE_CALENDAR_ID.value,PRODUCTION_SYNC_ENABLED:'false',PRODUCTION_AUTOMATION_ENABLED:'false'};
 await cf('/pages/projects/'+project,'PATCH',{deployment_configs:{production:{env_vars:Object.fromEntries(Object.entries(values).map(([k,value])=>[k,{type:'plain_text',value}])),d1_databases:{PORTAL_DB:{id:target}},compatibility_date:'2026-10-08',wrangler_config_hash:live.deployment_configs.production.wrangler_config_hash}},...(live.source?{source:{...live.source,config:{...live.source.config,production_deployments_enabled:false}}}:{})});writeFileSync(dir+'/binding-activated','true',{mode:0o600});const current=await cf('/pages/projects/'+project);require(current.deployment_configs.production.d1_databases.PORTAL_DB.id===target&&current.deployment_configs.production.env_vars.PRODUCTION_SYNC_ENABLED.value==='false','Live binding verification failed.');console.log('::notice::Authorized live binding prepared; synchronization and automation remain off.');}
async function rollback(){let before;try{before=JSON.parse(readFileSync(dir+'/before.json'));}catch{console.log('::notice::No live binding changed; rollback unnecessary.');return;}target=before.target;const live=await cf('/pages/projects/'+project);if(!Object.values(live.deployment_configs.production.d1_databases||{}).some(v=>v.id===target)&&live.canonical_deployment?.id===before.live.canonical_deployment?.id){console.log('::notice::Original production remains active.');return;}
 const vars=before.live.deployment_configs.production.env_vars,restore=Object.fromEntries(touched.map(k=>[k,vars[k]||null]));const dbs={...before.live.deployment_configs.production.d1_databases};if(!dbs.PORTAL_DB)dbs.PORTAL_DB=null;
 await cf('/pages/projects/'+project,'PATCH',{deployment_configs:{production:{env_vars:restore,d1_databases:dbs,compatibility_date:before.live.deployment_configs.production.compatibility_date,wrangler_config_hash:live.deployment_configs.production.wrangler_config_hash}},...(before.live.source?{source:before.live.source}:{})});if(live.canonical_deployment?.id!==before.live.canonical_deployment?.id)await cf('/pages/projects/'+project+'/deployments/'+before.live.canonical_deployment.id+'/rollback','POST');const current=await cf('/pages/projects/'+project);require(current.canonical_deployment?.id===before.live.canonical_deployment?.id,'Production rollback requires attention.');console.log('::notice::Original production deployment restored; durable data retained.');}
async function verify(){const before=JSON.parse(readFileSync(dir+'/before.json'));target=before.target;const live=await cf('/pages/projects/'+project),config=live.deployment_configs.production;require(live.canonical_deployment?.deployment_trigger?.metadata?.commit_hash===process.env.GITHUB_SHA&&config.d1_databases.PORTAL_DB.id===target&&config.env_vars.PRODUCTION_SYNC_ENABLED.value==='false'&&config.env_vars.PRODUCTION_AUTOMATION_ENABLED.value==='false','Live deployed configuration differs.');require(canonical((await cf('/pages/projects/auxesis-production-staging')).deployment_configs)===canonical(before.stage.deployment_configs),'Staging configuration changed.');
 const anon=await fetch(origin+'/api/portal/state',{redirect:'error'});require(anon.status===401,'Anonymous live state not denied.');const start=await fetch(origin+'/api/portal/auth/start',{redirect:'manual'});require(start.status===302,'Live sign-in start failed.');const location=new URL(start.headers.get('Location'));require(location.origin==='https://accounts.google.com'&&location.searchParams.get('redirect_uri')===origin+'/api/portal/auth/callback'&&location.searchParams.get('code_challenge_method')==='S256','Live OAuth redirect differs.');const flowHash=createHash('sha256').update(location.searchParams.get('state')).digest('base64url');const token=randomBytes(32).toString('base64url'),tokenHash=createHash('sha256').update(token).digest('base64url');let browser;
 try{await query(target,"INSERT INTO portal_sessions(token_hash,account_id,expires_at) VALUES(?1,?2,datetime('now','+5 minutes'))",[tokenHash,before.accounts[0].id]);const headers={Cookie:'__Host-auxesis_session='+token};const r=await fetch(origin+'/api/portal/state',{headers,redirect:'error'});require(r.ok,'Authenticated live state failed.');const state=await r.json();require(state.students.length===15&&state.lessons.length===200&&state.invoices.length===16&&state.payments.length===9&&state.settings.runtimeMode==='production'&&!state.settings.syncApplyEnabled&&!state.settings.automationEnabled,'Live inventory or disabled flags differ.');for(const kind of ['students','lessons','invoices','payments'])for(const original of before.records.filter(x=>x.kind===kind))require(canonical(state[kind].find(x=>x.id===original.id))===canonical(JSON.parse(original.data)),'Live business record differs.');
 const post=async(path,body)=>fetch(origin+'/api/portal/'+path,{method:'POST',redirect:'error',headers:{...headers,Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(body)});require((await post('sync',{mode:'apply'})).status===403&&(await post('command',{action:'updateInvoice'})).status===403,'Live writes are not blocked.');const {chromium}=await import('playwright');browser=await chromium.launch({headless:true,executablePath:'/usr/bin/google-chrome',args:['--no-sandbox']});const context=await browser.newContext({timezoneId:'America/Toronto'});await context.addCookies([{name:'__Host-auxesis_session',value:token,url:origin,secure:true,httpOnly:true,sameSite:'Lax'}]);const page=await context.newPage();let errors=0,mutations=0;page.on('pageerror',()=>errors++);await page.route('**/*',route=>{if(route.request().method()!=='GET'){mutations++;return route.abort();}return route.continue();});await page.clock.install({time:new Date('2026-10-09T12:00:00Z')});await page.goto(origin+'/portal/students/');await page.getByRole('heading',{name:'Students',exact:true}).waitFor();require(await page.locator('.student-card').count()===15,'Live student display differs.');require(await page.locator('[data-action="source-sync-apply"]').count()===0,'Live Apply visible.');await page.goto(origin+'/portal/dashboard/');await page.locator('[data-action="logout"]').waitFor();const section=page.locator('section').filter({has:page.getByRole('heading',{name:'Today’s lessons',exact:true})}),ids=await section.locator('a.lesson-row').evaluateAll(nodes=>nodes.map(n=>new URL(n.href).searchParams.get('id')));const day=v=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Toronto',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(v));const expected=state.lessons.filter(l=>day(l.start)==='2026-10-09').sort((a,b)=>Date.parse(a.start)-Date.parse(b.start));require(canonical(ids)===canonical(expected.map(l=>l.id)),'Live dashboard chronological order differs.');await page.goto(origin+'/portal/invoice/?id='+state.invoices[0].id);await page.locator('[data-action="logout"]').waitFor();require(errors===0&&mutations===0,'Live browser errors or mutation requests.');await browser.close();browser=null;
 for(const [table,expectedRows] of [['portal_records',before.records],['portal_accounts',before.accounts],['portal_audit',before.audits]])require(canonical(await query(target,'SELECT * FROM '+table+' ORDER BY id'))===canonical(expectedRows),'Post-cutover durable records changed.');const result={verifiedAt:new Date().toISOString(),productionUrl:origin,cutoverComplete:true,cloudflareNative:true,separateLiveDatabase:true,preservedRecords:371,students:15,lessons:200,invoices:16,payments:9,anonymousDenied:true,oauthPkce:true,authenticatedStateExact:true,dashboardChronologicalOrder:true,browserErrors:0,browserMutations:0,applyEnabled:false,liveSynchronizationEnabled:false,automationEnabled:false,financialChanges:0,calendarChanges:0,ownerFirstProductionGoogleSignInRequired:true};const authorization=await drive();const id=await savePrivate('Auxesis private production verification '+result.verifiedAt+'.json',Buffer.from(JSON.stringify(result)),authorization.access);await query(stageDb,'CREATE TABLE IF NOT EXISTS migration_production_validation(id TEXT PRIMARY KEY,file_id TEXT NOT NULL,target_database TEXT NOT NULL,created_at TEXT NOT NULL)');await query(stageDb,"INSERT INTO migration_production_validation(id,file_id,target_database,created_at) VALUES('production',?1,?2,?3) ON CONFLICT(id) DO UPDATE SET file_id=excluded.file_id,target_database=excluded.target_database,created_at=excluded.created_at",[id,target,result.verifiedAt]);console.log('::notice title=Production Portal verified::'+JSON.stringify(result));writeFileSync(dir+'/success.json',JSON.stringify(result),{mode:0o600});
 }finally{if(browser)await browser.close();await query(target,'DELETE FROM portal_sessions WHERE token_hash=?1',[tokenHash]);await query(target,'DELETE FROM portal_auth_flows WHERE token_hash=?1',[flowHash]);}}
try{const action=process.argv[2];if(action==='prepare')await prepare();else if(action==='activate')await activate();else if(action==='verify')await verify();else if(action==='rollback')await rollback();else throw Error('Unknown cutover action.');}catch(e){console.error('::error title=Production cutover::'+e.message);process.exitCode=1;}
