import { db } from './db';
import { sql } from 'kysely';
import { randomBytes, randomUUID, createHash } from 'crypto';
import { upload, getUrl, getInfo } from '@floot/storage';
import { createToken, publish } from '@floot/realtime';
import { FlootOAuthProvider } from './FlootOAuthProvider';

const SITE='https://auxesis-education.pages.dev';
const VERSION='2026-10-03';
type Item=Record<string,any>;
type Actor={id:string;email:string;name:string;role:string;parentId:string|null;studentId:string|null};
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
const secret=()=>randomBytes(32).toString('base64url');
const id=()=>randomUUID();
function fail(message='This record is not available.',status=403):never {throw Object.assign(new Error(message),{status});}
function text(v:unknown,max=1000,required=false){if(typeof v!=='string'||v.length>max||(required&&!v.trim()))fail('Please check the information entered.',400);return v.trim();}
const email=(v:unknown)=>{const s=text(v,254,true).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s))fail('Enter a valid email address.',400);return s;};
function num(v:unknown,min=0,max=100000){const n=Number(v);if(!Number.isFinite(n)||n<min||n>max)fail('Enter a valid amount or quantity.',400);return n;}
function date(v:unknown){const s=text(v,40,true);if(!Number.isFinite(Date.parse(s)))fail('Enter a valid date.',400);return new Date(s).toISOString();}
function zone(v:unknown){const s=text(v,80,true);try{new Intl.DateTimeFormat('en',{timeZone:s});}catch{fail('Use a location time zone, such as America/Toronto.',400);}return s;}
function pick(v:Item,keys:string[]){const out:Item={};for(const k of keys)if(v[k]!==undefined)out[k]=text(v[k],k==='body'?30000:3000);return out;}
const total=(i:Item)=>Number.isFinite(i.totalOverride)?i.totalOverride:Math.round(i.count*i.hoursPerLesson*i.rate*(1-i.discount/100)*100)/100;
function weekly(start:string,z:string,n:number){const parts=(d:Date)=>Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:z,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(d).map(p=>[p.type,p.value]));const p=parts(new Date(start)),local=Date.UTC(+p.year,+p.month-1,+p.day,+p.hour,+p.minute,+p.second)+n*7*86400000;let utc=local;for(let i=0;i<3;i++){const q=parts(new Date(utc));utc+=local-Date.UTC(+q.year,+q.month-1,+q.day,+q.hour,+q.minute,+q.second);}return new Date(utc).toISOString();}
function entitlement(s:Item){if(!s.endDate)return true;const d=new Date(s.endDate),original=d.getUTCDate();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+1);const max=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();d.setUTCDate(Math.min(original,max));return Date.now()<=d.getTime();}
function allowed(a:Actor,s:Item|undefined){return !!s&&(a.role==='admin'||a.role==='student'&&a.studentId===s.id||a.role==='parent'&&a.parentId===s.parentId);}
const admin=(a:Actor)=>{if(a.role!=='admin')fail();};
async function account(request:Request):Promise<Actor>{const token=request.headers.get('x-auxesis-session')||'';if(!/^[\w-]{43}$/.test(token))fail('Please sign in to continue.',401);const a=await db.selectFrom('portalSessions').innerJoin('portalAccounts','portalAccounts.id','portalSessions.accountId').select(['portalAccounts.id','email','name','role','parentId','studentId']).where('tokenHash','=',hash(token)).where('expiresAt','>',new Date()).where('enabled','=',true).executeTakeFirst();if(!a)fail('Please sign in to continue.',401);if(a.role!=='admin'){const settings=await db.selectFrom('portalRecords').select('data').where('id','=','settings').executeTakeFirst();if((settings?.data as Item)?.reviewMode)fail('Family access is paused while Amanda reviews the portal.',403);}return a;}
async function records(cx:any=db):Promise<Item[]>{const rows=await cx.selectFrom('portalRecords').selectAll().execute();return rows.map((r:any)=>({...r.data,id:r.id,_kind:r.kind}));}
async function put(cx:any,kind:string,d:Item){const clean={...d};delete clean._kind;await cx.insertInto('portalRecords').values({id:d.id,kind,studentId:kind==='students'?d.id:d.studentId||null,parentId:kind==='parents'?d.id:d.parentId||null,data:clean}).onConflict((oc:any)=>oc.column('id').doUpdateSet({data:clean,studentId:kind==='students'?d.id:d.studentId||null,parentId:kind==='parents'?d.id:d.parentId||null,revision:sql`portal_records.revision+1`,updatedAt:new Date()})).execute();}
function snapshot(a:Actor,all:Item[]){const state:Item={me:a,students:[],parents:[],lessons:[],threads:[],reports:[],invoices:[],payments:[],categories:[],resources:[],notifications:[],onboardings:[],billingHistory:[],billingArchive:[],importReviews:[],settings:{transfer:'',paypal:''}};const ss=all.filter(r=>r._kind==='students'&&allowed(a,r));const child=(sid:string)=>ss.some(s=>s.id===sid),access=a.role==='admin'||ss.some(entitlement);
 for(const raw of all){const r={...raw};delete r._kind;const k=raw._kind;let ok=a.role==='admin';if(!ok){if(k==='students')ok=child(r.id);if(k==='parents')ok=a.role==='parent'&&a.parentId===r.id;if(k==='lessons')ok=child(r.studentId);if(k==='threads')ok=r.kind==='student'?child(r.studentId):a.role==='parent'&&r.parentId===a.parentId;if(k==='reports')ok=a.role==='parent'&&child(r.studentId)&&r.status==='Published';if(k==='invoices')ok=a.role==='parent'&&child(r.studentId)&&r.issued;if(k==='payments')ok=a.role==='parent'&&child(r.studentId);if(k==='onboardings')ok=child(r.studentId);if(k==='categories'||k==='resources')ok=access;if(k==='notifications')ok=r.accountId===a.id;if(k==='settings')ok=a.role==='parent';}
 if(!ok)continue;
 if(k==='settings'){state.settings={transfer:r.transfer||'',paypal:r.paypal||'',contactEmail:r.contactEmail,...(a.role==='admin'?{reviewMode:r.reviewMode===true,importSummary:r.importSummary}: {})};continue;}
 if(a.role!=='admin'){for(const key of ['sourceMeta','sourceData','reviewFlags','migration','privateNotes','parentSource'])delete r[key];}
 if(a.role==='student'&&k==='students')for(const key of ['rate','currency','discount','purchased','used'])delete r[key];
 if(k==='onboardings')r.student=pick(r.student,['name','preferred','pronouns','email','country','zone','year','programme','subject','level','board','exam']);
 if(a.role==='student'&&k==='onboardings'){r.parent={};r.student=pick(r.student,['name','preferred','pronouns','email','country','zone','year','programme','subject','level','board','exam']);r.agreements=[];delete r.arrangements;}
 if(k==='invoices'&&r.issued&&r.status!=='Paid'&&new Date(r.due).getTime()<Date.now())r.status='Overdue';
 if(k==='threads'){r.unread=(r.unreadBy||[]).includes(a.id);delete r.unreadBy;}
 if(Array.isArray(state[k]))state[k].push(r);
 }
 state.entitled=access;state.policyVersion=VERSION;return state;}
async function viewer(request:Request,all:Item[]){
 const owner=await account(request),role=request.headers.get('x-auxesis-preview-role'),sid=request.headers.get('x-auxesis-preview-student');
 if(!role&&!sid)return {actor:owner,preview:null};
 admin(owner);if(!['student','parent'].includes(role||''))fail('Choose a student or parent preview.',400);
 const s=all.find(r=>r._kind==='students'&&r.id===sid);if(!s)fail();
 const p=all.find(r=>r._kind==='parents'&&r.id===s.parentId);if(role==='parent'&&!p)fail();
 const actor:Actor={id:'preview-'+role+'-'+s.id,email:role==='student'?s.email:p!.email,name:role==='student'?s.name:p!.name||'Parent / guardian',role:role!,studentId:role==='student'?s.id:null,parentId:role==='parent'?s.parentId:null};
 return {actor,preview:{role,studentId:s.id,studentName:s.name,ownerName:owner.name,readOnly:true}};
}
function previewReadOnly(request:Request){if(request.headers.has('x-auxesis-preview-role')||request.headers.has('x-auxesis-preview-student'))fail('This is a read-only preview. Return to Amanda’s workspace to make changes.',403);}
async function state(request:Request){const all=await records(),v=await viewer(request,all);return {...snapshot(v.actor,all),preview:v.preview};}
async function checkedFiles(cx:any,a:Actor,ids:unknown,kind:string,recordId:string){if(!Array.isArray(ids)||ids.length>3)fail('Attach up to three files.',400);const files:Item[]=[];for(const fid of ids){const f=await cx.selectFrom('portalFiles').selectAll().where('id','=',text(fid,80,true)).executeTakeFirst();if(!f||f.ownerId!==a.id||f.kind!==kind||f.recordId!==recordId)fail();const info=await getInfo({visibility:"private",filename:f.storageKey});if(!info.ok||!info.exists||info.sizeBytes!==f.bytes)fail('The attachment did not finish uploading. Please try again.',400);files.push({id:f.id,name:f.name,type:f.mime});}return files;}
async function command(request:Request,v:Item){previewReadOnly(request);const a=await account(request);const action=text(v.action,60,true),operation=text(v.operationId,80,true);if(!/^[a-zA-Z0-9-]{12,80}$/.test(operation))fail('Please retry this change.',400);
 const result=await db.transaction().execute(async cx=>{await sql`select pg_advisory_xact_lock(769463201)`.execute(cx);const prior=await cx.selectFrom('portalOperations').select('result').where('accountId','=',a.id).where('operationId','=',operation).executeTakeFirst();if(prior)return prior.result;
 const all=await records(cx);const find=(k:string,rid:string)=>{const r=all.find(r=>r._kind===k&&r.id===rid);if(!r)fail();return r;};const student=(sid:string)=>{const s=find('students',sid);if(!allowed(a,s))fail();return s;};let target:Item={},out:Item={ok:true};const save=async(k:string,r:Item)=>{await put(cx,k,r);const n=all.findIndex(x=>x.id===r.id);if(n<0)all.push({...r,_kind:k});else all[n]={...r,_kind:k};};
 const notify=async(accountId:string,message:string,extra:Item={})=>save('notifications',{id:id(),accountId,text:message,at:new Date().toISOString(),...extra});const notifyAdmin=async(message:string,extra:Item={})=>{for(const ad of await cx.selectFrom('portalAccounts').select('id').where('role','=','admin').where('enabled','=',true).execute())await notify(ad.id,message,extra);};
 if(action==='invite'){admin(a);if(all.find(r=>r.id==='settings')?.reviewMode)fail('Family access is paused during private review. Imported records can be previewed without invitations.',403);const pe=email(v.parentEmail),se=email(v.studentEmail);if(pe===se)fail('Use separate parent and student email addresses.',400);const existing=await cx.selectFrom('portalAccounts').selectAll().where('email','=',pe).executeTakeFirst();if(existing&&existing.role!=='parent')fail('This email already has a different role.',409);if(await cx.selectFrom('portalAccounts').select('id').where('email','=',se).executeTakeFirst())fail('The student email is already assigned.',409);
 const pid=existing?.parentId||id(),sid=id(),pn=text(v.parentName,200,true),sn=text(v.studentName,200,true);const p=existing?find('parents',pid):{id:pid,name:pn,email:pe,mobile:'',country:'',zone:'America/Toronto',contact:'Email',billingName:pn};const s={id:sid,parentId:pid,name:sn,preferred:text(v.preferred||sn.split(' ')[0],200),pronouns:'',email:se,country:'',zone:'America/Toronto',year:'',programme:text(v.programme||'',100),subject:text(v.subject||'',200),level:'',board:'',exam:'',rate:num(v.rate,0,10000),currency:['USD','CAD','GBP','EUR','AUD'].includes(v.currency)?v.currency:'USD',discount:0,purchased:0,used:0,day:'',time:'',length:60,frequency:'Weekly',startDate:new Date().toISOString(),endDate:null,goals:'',challenge:''};await save('parents',p);await save('students',s);if(!existing)await cx.insertInto('portalAccounts').values({id:id(),email:pe,name:pn,role:'parent',parentId:pid}).execute();await cx.insertInto('portalAccounts').values({id:id(),email:se,name:sn,role:'student',studentId:sid}).execute();await save('threads',{id:sid+'-student',kind:'student',studentId:sid,name:sn,messages:[],unreadBy:[]});if(!existing)await save('threads',{id:pid+'-parent',kind:'parent',parentId:pid,name:pn,messages:[],unreadBy:[]});await save('onboardings',{id:'onboarding-'+sid,studentId:sid,parentId:pid,step:0,parent:{...p},student:{...s},learning:{help:'',challenge:'',goals:'',dates:'',other:''},agreements:[],complete:false,arrangementsConfirmed:false});out.studentId=sid;out.invitation=SITE+'/portal/';
 }else if(action==='schedule'){admin(a);const s=student(v.studentId),start=date(v.start),count=num(v.count,1,24),hours=num(v.hours,.25,3);if(!Number.isInteger(count))fail('Enter a whole number of lessons.',400);for(let n=0;n<count;n++){const startAt=weekly(start,zone(v.zone||'America/Toronto'),n);if(all.some(r=>r._kind==='lessons'&&r.status==='Scheduled'&&r.studentId===s.id&&r.start===startAt))continue;await save('lessons',{id:id(),studentId:s.id,start:startAt,subject:text(v.subject||s.programme+' '+s.subject,200,true),hours,status:'Scheduled',planning:[],notes:{covered:'',outcome:'',next:''},resources:[],privateNotes:''});}
 }else if(['planning','notes','privateNotes','attachResource','complete','cancel','reschedule','tutorCancel','noShow'].includes(action)){target=find('lessons',v.id);const s=student(target.studentId);
 if(action==='planning'){if(a.role==='parent'||target.status!=='Scheduled')fail();target.planning.push({id:id(),author:a.name,authorId:a.id,at:new Date().toISOString(),text:text(v.text,10000,true),files:await checkedFiles(cx,a,v.files||[],'lesson',target.id)});await notifyAdmin(s.name+' added lesson planning.',{lessonId:target.id,type:'planning'});}
 if(action==='notes'){admin(a);target.notes=pick(v,['covered','outcome','next']);for(const k of ['covered','outcome','next'])target.notes[k]||='';}
 if(action==='privateNotes'){admin(a);target.privateNotes=text(v.text,20000);}
 if(action==='attachResource'){admin(a);find('resources',v.resourceId);if(!target.resources.includes(v.resourceId))target.resources.push(v.resourceId);}
 if(action==='complete'){admin(a);if(target.status!=='Scheduled')fail('This lesson has already been completed or cancelled.',409);target.status='Completed';target.completedAt=new Date().toISOString();s.used+=1;await save('students',s);}
 if(action==='cancel'){if(a.role!=='parent'||target.status!=='Scheduled'||Date.parse(target.start)<=Date.now())fail();const hours=(Date.parse(target.start)-Date.now())/3600000;target.status='Cancelled';target.cancelledAt=new Date().toISOString();target.cancelledBy=a.name;target.chargeable=hours<12;target.rescheduleRequired=hours>=12&&hours<168;if(target.chargeable){s.used+=1;await save('students',s);}await notifyAdmin(s.name+' cancelled a lesson · '+(target.chargeable?'Chargeable':target.rescheduleRequired?'Rescheduling applies':'No charge'),{type:'cancellation',lessonId:target.id});}
 if(action==='reschedule'){admin(a);if(target.status==='Completed')fail('Completed lessons retain their original dates.',409);target.start=date(v.start);target.hours=num(v.hours,.25,3);if(target.status==='Cancelled'){if(target.chargeable){s.used=Math.max(0,s.used-1);await save('students',s);}target.status='Scheduled';target.rescheduledAt=new Date().toISOString();target.chargeable=false;target.rescheduleRequired=false;}}
 if(action==='noShow'){admin(a);if(target.status!=='Scheduled'||Date.parse(target.start)>Date.now())fail();target.status='No-show';target.completedAt=new Date().toISOString();s.used+=1;await save('students',s);}
 if(action==='tutorCancel'){admin(a);if(target.status!=='Scheduled')fail();target.status='Cancelled';target.cancelledAt=new Date().toISOString();target.cancelledBy=a.name;target.chargeable=false;}
 await save('lessons',target);
 }else if(action==='message'||action==='markRead'){target=find('threads',v.id);if(target.kind==='student')student(target.studentId);else if(a.role!=='admin'&&!(a.role==='parent'&&target.parentId===a.parentId))fail();if(action==='message'){if(a.role==='parent'&&target.kind==='student'||a.role==='student'&&target.kind!=='student')fail();target.messages.push({id:id(),author:a.name,authorId:a.id,at:new Date().toISOString(),text:text(v.text,10000,true),files:await checkedFiles(cx,a,v.files||[],'thread',target.id)});const recipients=await cx.selectFrom('portalAccounts').selectAll().where('enabled','=',true).execute();target.unreadBy=recipients.filter(r=>r.id!==a.id&&(r.role==='admin'||target.kind==='parent'&&r.role==='parent'&&r.parentId===target.parentId||target.kind==='student'&&r.role==='student'&&r.studentId===target.studentId)).map(r=>r.id);for(const recipient of target.unreadBy)await notify(recipient,'New message from '+a.name,{type:'message',threadId:target.id});}else target.unreadBy=(target.unreadBy||[]).filter((rid:string)=>rid!==a.id);await save('threads',target);
 }else if(action==='profile'){const kind=v.kind==='parent'?'parents':'students';if(kind==='parents'){if(a.role!=='parent')fail();target=find(kind,a.parentId!);}else{target=student(v.id);if(a.role==='admin')fail();}const keys=kind==='parents'?['name','billingName','mobile','country','contact']:['name','preferred','pronouns','country'];Object.assign(target,pick(v,keys));if(v.zone!==undefined)target.zone=zone(v.zone);if(v.email!==undefined&&email(v.email)!==target.email)fail('Please ask Amanda to change the sign-in email.',400);await save(kind,target);if(target.name)await cx.updateTable('portalAccounts').set({name:target.name}).where(kind==='parents'?'parentId':'studentId','=',target.id).execute();
 }else if(action==='arrangements'){admin(a);target=student(v.id);Object.assign(target,pick(v,['day','time','frequency']));target.length=num(v.length,15,180);target.rate=num(v.rate,.01,10000);target.discount=num(v.discount,0,100);target.purchased=num(v.purchased,0,10000);if(!['USD','CAD','GBP','EUR','AUD'].includes(v.currency))fail('Choose a supported currency.',400);target.currency=v.currency;target.startDate=v.startDate?date(v.startDate):target.startDate;target.endDate=v.endDate?date(v.endDate+'T23:59:59Z'):null;await save('students',target);const on=all.find(x=>x._kind==='onboardings'&&x.studentId===target!.id);if(on){on.arrangementsConfirmed=false;await save('onboardings',on);}
 }else if(action==='report'){admin(a);const s=student(v.studentId),month=text(v.month,80,true),existing=all.find(r=>r._kind==='reports'&&r.studentId===s.id&&r.month===month);target={id:existing?.id||id(),studentId:s.id,month,body:text(v.body,30000,true),status:v.publish?'Published':'Draft',publishedAt:v.publish?new Date().toISOString():null};await save('reports',target);if(v.publish)for(const p of await cx.selectFrom('portalAccounts').select('id').where('parentId','=',s.parentId).where('role','=','parent').execute())await notify(p.id,'A monthly report is ready for '+s.preferred,{type:'report',studentId:s.id});
 }else if(action==='category'){admin(a);const name=text(v.programme,100,true),subject=text(v.subject,100,true);target=all.find(r=>r._kind==='categories'&&r.name.toLowerCase()===name.toLowerCase())||{id:id(),name,subjects:[]};if(!target.subjects.includes(subject))target.subjects.push(subject);await save('categories',target);
 }else if(action==='resource'){admin(a);const rid=text(v.id,80,true);if(all.some(r=>r.id===rid))fail('This resource already exists.',409);target={id:rid,...pick(v,['programme','subject','category','subcategory','type','title','description','body']),files:await checkedFiles(cx,a,v.files||[],'resource',rid)};for(const k of ['programme','subject','title'])text(target[k],300,true);await save('resources',target);const cat=all.find(r=>r._kind==='categories'&&r.name===target!.programme)||{id:id(),name:target.programme,subjects:[]};if(!cat.subjects.includes(target.subject))cat.subjects.push(target.subject);await save('categories',cat);
 }else if(action==='onboarding'){target=find('onboardings',v.id);const s=student(target.studentId),step=num(v.step,0,4);if(a.role==='student'){if(step!==2)fail();target.learning=pick(v,['help','challenge','goals','dates','other']);s.goals=target.learning.goals||s.goals;s.challenge=target.learning.challenge||s.challenge;await save('students',s);}else{if(a.role!=='parent')fail();if(step>target.step)fail('This step has changed. Reload and try again.',409);if(step===0){target.parent={...target.parent,...pick(v,['name','mobile','country','contact','billingName']),zone:zone(v.zone)};await save('parents',target.parent);}if(step===1){if(v.email!==s.email)fail('Please ask Amanda to change the student sign-in email.',400);target.student={...target.student,...pick(v,['name','preferred','pronouns','country','year','programme','subject','level','board','exam']),zone:zone(v.zone)};Object.assign(s,pick(target.student,['name','preferred','pronouns','country','year','programme','subject','level','board','exam','zone']));await save('students',s);}if(step===2){target.learning=pick(v,['help','challenge','goals','dates','other']);s.goals=target.learning.goals||s.goals;s.challenge=target.learning.challenge||s.challenge;await save('students',s);}if(step===3){if(v.confirm!==true)fail('Please confirm the tutoring arrangements.',400);target.arrangementsConfirmed=true;target.arrangementsAt=new Date().toISOString();target.arrangements={day:s.day,time:s.time,length:s.length,frequency:s.frequency,rate:s.rate,currency:s.currency,discount:s.discount};}if(step===4){if(v.policyVersion!==VERSION)fail('Please reload the current policy wording before acknowledging it.',409);if(!target.arrangementsConfirmed||!['tutoring','technology','privacy'].every(p=>v[p]===true))fail('Please acknowledge each policy separately.',400);target.agreements=['tutoring','technology','privacy'].map(policy=>({policy,version:VERSION,who:a.name,accountId:a.id,at:new Date().toISOString()}));target.complete=true;}else target.step=Math.max(target.step,step+1);}await save('onboardings',target);
 }else if(action==='invoice'){admin(a);const s=student(v.studentId),existing=all.find(r=>r._kind==='invoices'&&r.studentId===s.id&&!r.issued);if(existing)out.invoiceId=existing.id;else{const count=num(v.count,1,24);if(!Number.isInteger(count)||s.rate<=0)fail('Set an agreed rate and whole number of lessons first.',400);const first=date(v.first+'T12:00:00Z'),due=date(v.due+'T23:59:59Z');target={id:id(),studentId:s.id,number:v.first.replace(/-/g,'')+'-'+s.preferred+'-'+id().slice(0,4),issued:false,date:new Date().toISOString(),due,status:'Draft',count,hoursPerLesson:num(v.hours,.25,3),rate:s.rate,discount:s.discount,currency:s.currency,received:0,paidAt:null,method:'',credit:0,balanceApplied:false,dates:Array.from({length:count},(_,n)=>new Date(Date.parse(first)+n*7*86400000).toISOString())};await save('invoices',target);out.invoiceId=target.id;}
 }else if(action==='issue'||action==='payment'){admin(a);target=find('invoices',v.id);if(target.importReview)fail('Review and reconcile this imported invoice before issuing it or changing its payments.',409);const s=student(target.studentId);if(action==='issue'){if(target.issued)fail('This invoice has already been issued.',409);target.issued=true;target.status='Unpaid';target.date=new Date().toISOString();for(const p of await cx.selectFrom('portalAccounts').select('id').where('parentId','=',s.parentId).where('role','=','parent').execute())await notify(p.id,'An invoice is ready for '+s.preferred,{type:'invoice',invoiceId:target.id});}else{if(!target.issued)fail('Issue this invoice before recording payment.',409);const amount=Math.round(num(v.amount,.01,100000)*100)/100;target.received=Math.round((target.received+amount)*100)/100;target.paidAt=date(v.date+'T12:00:00Z');target.method=text(v.method,100,true);target.credit=Math.max(0,target.received-total(target));target.status=target.received>=total(target)?'Paid':Date.parse(target.due)<Date.now()?'Overdue':'Partially Paid';const apply=target.status==='Paid'&&!target.balanceApplied;await save('payments',{id:id(),invoiceId:target.id,studentId:s.id,amount,currency:target.currency,date:target.paidAt,method:target.method,lessons:apply?target.count:0});if(apply){s.purchased+=target.count;target.balanceApplied=true;await save('students',s);}}await save('invoices',target);
 }else if(action==='settings'){admin(a);target=find('settings','settings');target.transfer=text(v.transfer,5000);target.paypal=text(v.paypal,500);if(target.paypal){const u=new URL(target.paypal);if(u.protocol!=='https:'||!['paypal.me','www.paypal.com','paypal.com'].includes(u.hostname))fail('Use a PayPal HTTPS link.',400);}await save('settings',target);
 }else if(action==='revoke'){admin(a);const sid=text(v.studentId,80,true);student(sid);await cx.updateTable('portalAccounts').set({enabled:false}).where('studentId','=',sid).execute();
 }else fail('This action is not available.',400);
 await cx.insertInto('portalAudit').values({id:id(),accountId:a.id,action,recordId:target?.id||out.studentId||null}).execute();await cx.insertInto('portalOperations').values({accountId:a.id,operationId:operation,result:out}).execute();return out;});
 // Events carry no private record content. Every refresh rechecks the current session.
 const accounts=await db.selectFrom('portalAccounts').select('id').where('enabled','=',true).execute();for(const actor of accounts)try{await publish('account:'+actor.id,{type:'refresh'});}catch{console.error('Portal live update unavailable');}return result;
}
async function files(request:Request,v:Item){previewReadOnly(request);const a=await account(request),all=await records();const kind=text(v.kind,20,true),rid=text(v.recordId,80,true);const r=all.find(r=>r.id===rid);if(kind==='resource'){admin(a);}else if(kind==='lesson'){if(!r||r._kind!=='lessons'||!allowed(a,all.find(s=>s._kind==='students'&&s.id===r.studentId))||a.role==='parent'||r.status!=='Scheduled')fail();}else if(kind==='thread'){if(!r||r._kind!=='threads'||a.role==='parent'&&r.kind==='student')fail();if(a.role!=='admin'&&!(r.kind==='student'&&a.role==='student'&&r.studentId===a.studentId||r.kind==='parent'&&a.role==='parent'&&r.parentId===a.parentId))fail();}else fail();
 const name=text(v.name,150,true).replace(/[\r\n/\\]/g,'_'),bytes=num(v.bytes,1,2097152),mime=text(v.mime,150,true);const types=['image/jpeg','image/png','image/webp','image/gif','application/pdf','text/plain','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.presentationml.presentation','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'];if(!types.includes(mime))fail('Use a photo, PDF, text or Office document.',400);const fid=id(),prepared=await upload({visibility:'private',filename:fid+'-'+name,contentType:mime,sizeBytes:bytes,ifAbsent:true});if(!prepared.ok)fail('The upload could not be prepared.',503);await db.insertInto('portalFiles').values({id:fid,storageKey:fid+'-'+name,name,mime,bytes,kind,recordId:rid,ownerId:a.id}).execute();return {id:fid,name,type:mime,presignedUrl:prepared.presignedUrl,headers:prepared.headers};}
async function file(request:Request){const all=await records(),a=(await viewer(request,all)).actor,fid=new URL(request.url).searchParams.get('id')||'',f=await db.selectFrom('portalFiles').selectAll().where('id','=',fid).executeTakeFirst();if(!f)fail();const visible=snapshot(a,all);const r=[...visible.lessons,...visible.threads,...visible.resources].find((r:Item)=>r.id===f.recordId);const linked=r&&JSON.stringify(r).includes('"id":"'+f.id+'"');if(!linked||f.kind==='resource'&&!visible.entitled)fail();const signed=await getUrl({visibility:'private',filename:f.storageKey,expiresInSeconds:20});if(!signed.ok)fail('The file could not be opened.',503);return {url:signed.url,name:f.name,mime:f.mime};}
async function start(request:Request,v:Item){const nonceHash=text(v.nonceHash,64,true);if(!/^[a-f0-9]{64}$/.test(nonceHash))fail('Please retry signing in.',400);const ip=request.headers.get('x-auxesis-client')||'direct';const key=hash(ip+Math.floor(Date.now()/600000));const rate=await db.insertInto('portalRateLimits').values({key,count:1,expiresAt:new Date(Date.now()+600000)}).onConflict(oc=>oc.column('key').doUpdateSet({count:sql`portal_rate_limits.count+1`})).returning('count').executeTakeFirstOrThrow();if(rate.count>20)fail('Please wait a few minutes before trying again.',429);const redirect=new URL('/_api/auth/oauth_callback',request.url).href;const provider=new FlootOAuthProvider(redirect),state=secret(),p=provider.generateAuthorizationUrl(state);await db.insertInto('portalAuthFlows').values({tokenHash:hash(state),phase:'oauth',verifier:p.codeVerifier,nonceHash,expiresAt:new Date(Date.now()+600000)}).execute();return {url:p.url};}
async function callback(request:Request){try{const q=new URL(request.url).searchParams,state=q.get('state')||'',code=q.get('code')||'';if(!state||!code)fail();const flow=await db.deleteFrom('portalAuthFlows').where('tokenHash','=',hash(state)).where('phase','=','oauth').where('expiresAt','>',new Date()).returningAll().executeTakeFirst();if(!flow)fail();const redirect=new URL('/_api/auth/oauth_callback',request.url).href,provider=new FlootOAuthProvider(redirect),tokens=await provider.exchangeCodeForTokens(code,redirect,flow.verifier||undefined),info=await provider.fetchUserInfo(tokens);if(info.email_verified===false)fail();const user=provider.mapUserData(info);const a=await db.selectFrom('portalAccounts').selectAll().where('email','=',email(user.email)).where('enabled','=',true).executeTakeFirst();if(!a||a.providerId&&a.providerId!==user.providerUserId)return Response.redirect(SITE+'/portal/#error=not-invited',302);await db.updateTable('portalAccounts').set({providerId:user.providerUserId}).where('id','=',a.id).execute();const handoff=secret();await db.insertInto('portalAuthFlows').values({tokenHash:hash(handoff),phase:'handoff',nonceHash:flow.nonceHash,accountId:a.id,expiresAt:new Date(Date.now()+60000)}).execute();return Response.redirect(SITE+'/portal/#signin='+handoff,302);}catch{return Response.redirect(SITE+'/portal/#error=signin',302);}}
async function redeem(v:Item){const t=text(v.token,60,true),nonce=text(v.nonceHash,64,true);const flow=await db.deleteFrom('portalAuthFlows').where('tokenHash','=',hash(t)).where('nonceHash','=',nonce).where('phase','=','handoff').where('expiresAt','>',new Date()).returningAll().executeTakeFirst();if(!flow?.accountId)fail('This sign-in has expired. Please try again.',401);const a=await db.selectFrom('portalAccounts').select('id').where('id','=',flow.accountId).where('enabled','=',true).executeTakeFirst();if(!a)fail();const token=secret();await db.insertInto('portalSessions').values({tokenHash:hash(token),accountId:a.id,expiresAt:new Date(Date.now()+7*86400000)}).execute();return {token};}
async function logout(request:Request){await db.deleteFrom('portalSessions').where('tokenHash','=',hash(request.headers.get('x-auxesis-session')||'')).execute();return {ok:true};}
async function realtime(request:Request){const a=await account(request);return createToken({userId:a.id,channels:['account:'+a.id],ttlSeconds:300});}
function response(value:unknown,status=200){return new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});}
async function handle(request:Request,fn:(r:Request,v:Item)=>Promise<unknown>){try{let v={};if(request.method==='POST'){if(request.headers.get('content-type')?.split(';')[0]!=='application/json')fail('Send JSON data.',415);const body=await request.text();if(body.length>150000)fail('This request is too large.',413);v=JSON.parse(body);}return response(await fn(request,v));}catch(e:any){return response({error:e.status?e.message:'This change could not be saved. Please retry.'},e.status||500);}}
export const portalCore={account,state,command,files,file,start,callback,redeem,logout,realtime,handle,hash,snapshot,entitlement,weekly,viewer,previewReadOnly};

